# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/wbhs614/TestB.git'
source 'https://github.com/wbhs614/WBRealm.git'

platform :ios, '9.0'
target 'TestDemo' do
  use_frameworks!
  pod 'AFNetworking', '~> 3.2.1'
  pod 'WBRealm'

  # Pods for TestDemo

  target 'TestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoUITests' do
    # Pods for testing
  end

end
