source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/wbhs614/TestB.git'


target ‘TestDemo'do
    pod 'TestA', '~> 3.2.1'
end


